In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df1=pd.read_csv('/content/drive/MyDrive/C&T train dataset.csv')
dframe=pd.read_csv('/content/drive/MyDrive/C&T test dataset.csv')
df=df=pd.concat([df1,dframe],axis=1)
df

,sno,acc_info,duration_month,credit_history,purpose,savings_acc,employment_st,poi,personal_status,gurantors,...,resident_since,property_type,age,installment_type,housing_type,credits_no,job_type,liables,telephone,foreigner
0,1,A11,6,A34,A43,A65,A75,4.0,A93,A101,...,4.0,A124,54.0,A143,A153,2.0,A173,2.0,A191,A201
1,2,A12,48,A32,A43,A61,A73,2.0,A92,A101,...,4.0,A121,48.0,A141,A151,2.0,A172,1.0,A192,A201
2,3,A14,12,A34,A46,A61,A74,2.0,A93,A101,...,4.0,A122,24.0,A143,A152,2.0,A173,1.0,A191,A201
3,4,A11,42,A32,A42,A61,A74,2.0,A93,A103,...,4.0,A123,35.0,A143,A152,2.0,A173,1.0,A191,A201
4,5,A11,24,A33,A40,A61,A73,3.0,A93,A101,...,2.0,A121,24.0,A143,A151,1.0,A171,1.0,A191,A201
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,796,A14,9,A32,A42,A62,A72,2.0,A92,A101,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
796,797,A11,18,A32,A41,A65,A75,1.0,A93,A101,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
797,798,A14,12,A34,A42,A61,A72,2.0,A92,A101,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
798,799,A14,24,A33,A40,A65,A75,4.0,A94,A101,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
799,800,A12,9,A32,A40,A65,A72,4.0,A93,A101,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.isna().sum()

sno                   0
acc_info              0
duration_month        0
credit_history        0
purpose               0
savings_acc           0
employment_st         8
poi                  12
personal_status       0
gurantors             8
resident_since        0
property_type         0
age                   4
installment_type      0
housing_type          7
credits_no            0
job_type              0
liables               0
telephone             0
foreigner             0
Group_no              0
sno                 600
acc_info            600
duration_month      600
credit_history      600
purpose             600
savings_acc         600
employment_st       605
poi                 605
personal_status     600
gurantors           600
resident_since      600
property_type       600
age                 602
installment_type    600
housing_type        608
credits_no          600
job_type            600
liables             600
telephone           600
foreigner           600
dtype: int64

In [ ]:
df.dtypes

sno                   int64
acc_info             object
duration_month        int64
credit_history       object
purpose              object
savings_acc          object
employment_st        object
poi                 float64
personal_status      object
gurantors            object
resident_since        int64
property_type        object
age                 float64
installment_type     object
housing_type         object
credits_no            int64
job_type             object
liables               int64
telephone            object
foreigner            object
Group_no              int64
sno                 float64
acc_info             object
duration_month      float64
credit_history       object
purpose              object
savings_acc          object
employment_st        object
poi                 float64
personal_status      object
gurantors            object
resident_since      float64
property_type        object
age                 float64
installment_type     object
housing_type         object
credits_no          float64
job_type             object
liables             float64
telephone            object
foreigner            object
dtype: object

In [ ]:
df = df.dropna()
df

,sno,acc_info,duration_month,credit_history,purpose,savings_acc,employment_st,poi,personal_status,gurantors,...,resident_since,property_type,age,installment_type,housing_type,credits_no,job_type,liables,telephone,foreigner
0,1,A11,6,A34,A43,A65,A75,4.0,A93,A101,...,4.0,A124,54.0,A143,A153,2.0,A173,2.0,A191,A201
1,2,A12,48,A32,A43,A61,A73,2.0,A92,A101,...,4.0,A121,48.0,A141,A151,2.0,A172,1.0,A192,A201
2,3,A14,12,A34,A46,A61,A74,2.0,A93,A101,...,4.0,A122,24.0,A143,A152,2.0,A173,1.0,A191,A201
3,4,A11,42,A32,A42,A61,A74,2.0,A93,A103,...,4.0,A123,35.0,A143,A152,2.0,A173,1.0,A191,A201
4,5,A11,24,A33,A40,A61,A73,3.0,A93,A101,...,2.0,A121,24.0,A143,A151,1.0,A171,1.0,A191,A201
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,194,A14,6,A32,A43,A61,A74,2.0,A94,A101,...,3.0,A122,30.0,A143,A152,1.0,A174,1.0,A192,A201
194,195,A12,45,A32,A43,A62,A73,4.0,A93,A103,...,3.0,A123,50.0,A143,A152,1.0,A173,1.0,A192,A201
195,196,A12,9,A34,A46,A61,A75,2.0,A92,A101,...,4.0,A121,31.0,A143,A152,1.0,A172,1.0,A191,A201
198,199,A12,24,A32,A41,A65,A75,4.0,A93,A101,...,4.0,A124,23.0,A143,A153,1.0,A173,1.0,A192,A201
199,200,A12,18,A33,A42,A61,A75,4.0,A91,A101,...,4.0,A123,27.0,A143,A152,1.0,A173,1.0,A191,A201

In [ ]:
df.isna().sum()

sno                 0
acc_info            0
duration_month      0
credit_history      0
purpose             0
savings_acc         0
employment_st       0
poi                 0
personal_status     0
gurantors           0
resident_since      0
property_type       0
age                 0
installment_type    0
housing_type        0
credits_no          0
job_type            0
liables             0
telephone           0
foreigner           0
Group_no            0
sno                 0
acc_info            0
duration_month      0
credit_history      0
purpose             0
savings_acc         0
employment_st       0
poi                 0
personal_status     0
gurantors           0
resident_since      0
property_type       0
age                 0
installment_type    0
housing_type        0
credits_no          0
job_type            0
liables             0
telephone           0
foreigner           0
dtype: int64

In [ ]:
df.drop(['sno','acc_info','employment_st'],axis=1,inplace=True)
df

<ipython-input-7-9536e571cd6a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(['sno','acc_info','employment_st'],axis=1,inplace=True)

,duration_month,credit_history,purpose,savings_acc,poi,personal_status,gurantors,resident_since,property_type,age,...,resident_since,property_type,age,installment_type,housing_type,credits_no,job_type,liables,telephone,foreigner
0,6,A34,A43,A65,4.0,A93,A101,4,A121,67.0,...,4.0,A124,54.0,A143,A153,2.0,A173,2.0,A191,A201
1,48,A32,A43,A61,2.0,A92,A101,2,A121,22.0,...,4.0,A121,48.0,A141,A151,2.0,A172,1.0,A192,A201
2,12,A34,A46,A61,2.0,A93,A101,3,A121,49.0,...,4.0,A122,24.0,A143,A152,2.0,A173,1.0,A191,A201
3,42,A32,A42,A61,2.0,A93,A103,4,A122,45.0,...,4.0,A123,35.0,A143,A152,2.0,A173,1.0,A191,A201
4,24,A33,A40,A61,3.0,A93,A101,4,A124,53.0,...,2.0,A121,24.0,A143,A151,1.0,A171,1.0,A191,A201
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,6,A32,A43,A61,2.0,A94,A101,2,A121,29.0,...,3.0,A122,30.0,A143,A152,1.0,A174,1.0,A192,A201
194,45,A32,A43,A62,4.0,A93,A103,4,A122,21.0,...,3.0,A123,50.0,A143,A152,1.0,A173,1.0,A192,A201
195,9,A34,A46,A61,2.0,A92,A101,3,A123,34.0,...,4.0,A121,31.0,A143,A152,1.0,A172,1.0,A191,A201
198,24,A32,A41,A65,4.0,A93,A101,4,A124,36.0,...,4.0,A124,23.0,A143,A153,1.0,A173,1.0,A192,A201
199,18,A33,A42,A61,4.0,A91,A101,3,A124,40.0,...,4.0,A123,27.0,A143,A152,1.0,A173,1.0,A191,A201

In [ ]:
credit_history = df['credit_history'].values

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['purpose'] = le.fit_transform(df['purpose'])

ValueError: y should be a 1d array, got an array of shape (173, 2) instead.